### ISSUE TITLE
feat-pointing 브랜치에서 test_pointing.py 생성

### ISSUE THREAD

**Issue by Namhoon-Cho** [Looking-4-Attention/AttentionMe#5]
제목과 같이 테스트용으로 만든 파일인데, 저희 2차 회의때 코드 작동되는 거 보여드린 다음에는 삭제하고 머지하면 될 것 같아요!
의견 남겨주시면 pr 전에 참고할게요~

commit [c63d69a]

**Comment by hyun1227** [comment]
네 좋아요 
합칠 때 삭제하면 좋을 것 같아요
