### ISSUE TITLE
crop과 zoom_in 기능 유사

### ISSUE THREAD

**Issue by wwwwje2008** [Looking-4-Attention/AttentionMe#6]
crop과 zoom_in 기능의 동작이 유사한 것 같습니당
두 기능을 통합하거나 기능을 바꿔야 할 것 같아요

의견 부탁드립니다!

**Comment by Namhoon-Cho** [comment]
확실히 그렇군요~ 얘기 한 번 해봐야겠어요!

**Comment by Namhoon-Cho** [comment]
@iamdami @hyun1227

**Comment by iamdami** [comment]
crop: 객체를 포함한 최소화된 bbox 추출
zoom_in: 객체 탐지해 bbox 확대해 추출
인 것 같은데 정말 비슷하네요!

그럼 crop은 그냥 두고, remove_background 기능을 하나 더 만드는 건 어때요?
remove_background: 배경과 전경을 분리된 상태에서(segmentation) 전경만 두고 배경을 없애(투명하게)버리는 거죠!
일종의 opencv grabcut()과 비슷한 기능으로요

**Comment by wwwwje2008** [comment]
오 remove_backgroud 좋네요!
그렇게 하면 될 것 같습니다 ㅎㅎ

**Comment by iamdami** [comment]
remove_background() 추가했습니다 !
