### ISSUE TITLE
segmentation 개선 제안

### ISSUE THREAD

**Issue by wwwwje2008** [Looking-4-Attention/AttentionMe#7]
segment_person 함수를 실행하면 사람이 한 명 밖에 없어도 여러 객체가 탐지되는 문제가 있네요
그리고 탐지된 객체를 보여주는 게 아니라 Bounding Box만 보여주니까 선택한 객체가 무슨 객체인지 알기 힘드네용

1. 불필요한 객체를 탐지하지 않게 수정하고
2. 탐지된 객체가 뭔지 볼 수 있게 미리보기 기능도 추가하면

될 것 같습니다!

1번 문제는 제가 수정해서 main에 업로드 해두겠습니다!

**Comment by iamdami** [comment]
네 좋아요! 
스레시홀드나 스코어값을 조정해서 좀 더 정확한 객체를 추출하면 좋을 거 같아요 👍

**Comment by wwwwje2008** [comment]
1번 문제 해결해서 커밋했습니다!
2번 문제도 고쳐볼게요

**Comment by wwwwje2008** [comment]
2번 문제도 해결 완료했습니다!
#08ccdb2
